version: '3.8'
services:
  postgresdb:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432: ${PG_PORT}
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
  redisdb:
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASS} 
    ports:
      - 6379: ${REDIS_PORT}
    volumes:
      - monster_redis:db

volumes:
  monster_redis: